<?php

/**
 * Implements hook_local_tasks_alter().
 */
function pd_vendor_local_tasks_alter(&$local_tasks) {
  unset($local_tasks['user.login']);
  unset($local_tasks['user.register']);
  unset($local_tasks['user.pass']);
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function pd_vendor_field_widget_profile_form_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $items = $context['items'];
  if (!$items->getValue()[0]) {
    if (\Drupal::currentUser()->isAuthenticated()) {
      $element['#access'] = FALSE;
    }
  }

}
